### PR TITLE
FLUID-6316: Move fluid-grunt-eslint to main dependencies block.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [FLUID-6316](https://issues.fluidproject.org/browse/FLUID-6316) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
@amb26, here is the small pull I mentioned.  I'd appreciate it if you quickly cut a dev release so I can confirm the problem is fixed.

**Comment by the-t-in-rtf** [comment]
Sorry, I was missing email information on some early commits and rebasing didn't make the CLA assistant happy .  We can either knowingly walk past that warning or I can try to resubmit the pull with only clean commits.

**Comment by jobara** [comment]
@the-t-in-rtf if you don't need the commit history for all the intermediate commits you could just squash everything down with a soft reset and recommit with the correct setup. Then force pushing to your branch and seeing if that works.

**Comment by the-t-in-rtf** [comment]
After various attempts to squash, I'll resubmit from a clean branch.

**Comment by the-t-in-rtf** [comment]
Here's [the new pull](https://github.com/fluid-project/eslint-config-fluid/pull/5).

**Pull request closed without merging**
