### PR TITLE
GH-19: Migrate away from using Grunt for internal linting (resolves #19).

### LINKED ISSUE #19: Migrate away from using Grunt.
As discussed in #18, we should be able to migrate away from using `Grunt` in this package.  To quote @greatislander:

>This is not strictly related to this PR but I wonder if it might be worth removing grunt etc if it's only being used for linting this package and eslint is now a dependency? If we were to do so we could change the lint script to eslint with an appropriate glob rule to target all the JS and JSON files in this package.

I think we should discuss briefly, as in the `npx` era we also have the option to lint everything with `fluid-lint-all` without creating a circular dependency.

### PR DESCRIPTION
**Pull request by duhrer**
See #19 for background.

### CODE REVIEW

**Comment by duhrer** [comment]
In order to migrate away from using `Grunt`, I had to find a way to lint JSON files, which we previously used `grunt-jsonlint` for.  I initially wasn't happy with the output using `jsonlint` directly, and so used `fluid-lint-all` via `npx`.  After further experimentation, I came up with a set of flags for `jsonlint` and reverted to using that.

**Comment by duhrer** [comment]
Just to summarise, since I didn't use `fluid-lint-all` or `npm-run-all`, currently the JSON checks won't run if the ESLint checks fail.  We also don't get a summary on successful validation, which earlier would have been something like:

```
> grunt lint

Running "eslint:all" (eslint) task

Running "jsonlint:all" (jsonlint) task
>> 5 files lint free.
```

**Comment by amb26** [comment]
> Just to summarise, since I didn't use `fluid-lint-all` or `npm-run-all`, currently the JSON checks won't run if the ESLint checks fail. We also don't get a summary on successful validation, which earlier would have been something like:
> 
> ```
> > grunt lint
> 
> Running "eslint:all" (eslint) task
> 
> Running "jsonlint:all" (jsonlint) task
> >> 5 files lint free.
> ```

Would be good to get the file count report back since this is a very useful sanity check - especially in the case something about the globs ends up hitting zero files.

**Comment by duhrer** [comment]
Are we OK with using `fluid-lint-all` via `npx`?  I'd rather not create a circular dependency.

**Review by greatislander — APPROVED** [review]

**Comment by greatislander** [comment]
Hi @duhrer and @amb26, I would love to get this and #21 merged. Any thoughts?

**Comment by jobara** [comment]
@duhrer and @amb26, I was looking at this a bit today. In my searching I came across this old issue https://github.com/eslint/eslint/issues/13725. Which Made me remember looking into something like this before, and I dug up https://github.com/fluid-project/fluid-grunt-lint-all/blob/1b2274fe30274d116340efcb5b48130e6227a485/formatters/stylish/stylish.js#L4

Instead of creating our own formatter or using this fork though there was talk of other formatters so something like [eslint-formatter-multiple](https://www.npmjs.com/package/eslint-formatter-multiple) could be used in conjunction with [eslint-summary](https://www.npmjs.com/package/eslint-summary) to output the standard stylish summary and a summary line. 

This is just for ESLint though, which I suppose would mean moving away from jsonlint and using something like [eslint-plugin-json](https://www.npmjs.com/package/eslint-plugin-json) to lint the js files. 

I guess we could also use fluid-lint-all with npx. I'm not sure that it matters that fluid-lint-all would depend on this.

**Comment by jobara** [comment]
An updated package.json file which includes the tools I mentioned above:

```json
{
    "name": "eslint-config-fluid",
    "version": "2.1.3",
    "description": "fluid-project eslint configuration",
    "main": "index.js",
    "engines": {
        "node": ">=14.0.0"
    },
    "repository": {
        "type": "git",
        "url": "git+https://github.com/fluid-project/eslint-config-fluid.git"
    },
    "keywords": [
        "eslint",
        "eslintconfig",
        "fluid",
        "fluid-project"
    ],
    "scripts": {
        "lint": "npm run lint:eslint && npm run lint:json",
        "lint:eslint": "eslint --format eslint-formatter-multiple *.js",
        "lint:json": "eslint --format eslint-formatter-multiple --ignore-pattern '!.eslintrc-*.json' --config ./.eslintrc-json.json *.json .*.json"
    },
    "eslint-formatter-multiple": {
        "formatters": [
            {
                "name": "stylish",
                "output": "console"
            },
            {
                "name": "node_modules/eslint-summary/summary.js",
                "output": "console"
            }
        ]
    },
    "author": "Fluid Project",
    "license": "BSD-3-Clause",
    "bugs": {
        "url": "https://issues.fluidproject.org/projects/FLUID/issues"
    },
    "homepage": "http://fluidproject.org",
    "dependencies": {
        "@stylistic/eslint-plugin-js": "1.0.0",
        "eslint": "8.53.0",
        "eslint-plugin-jsdoc": "39.3.13"
    },
    "devDependencies": {
        "eslint-formatter-multiple": "^2.0.0",
        "eslint-plugin-json": "^4.0.1",
        "eslint-summary": "^1.0.0"
    }
}
```

.eslintrc-json.json file to configure eslint-plugin-json

```json
{
    "extends": [
        "plugin:json/recommended-legacy"
    ]
}
```

Running `npm run lint` would output the following:

```log
npm run lint     

> eslint-config-fluid@2.1.3 lint
> npm run lint:eslint && npm run lint:json


> eslint-config-fluid@2.1.3 lint:eslint
> eslint --format eslint-formatter-multiple *.js



3 files checked.  3 passed.  0 failed.


> eslint-config-fluid@2.1.3 lint:json
> eslint --format eslint-formatter-multiple --ignore-pattern '!.eslintrc-*.json' --config ./.eslintrc-json.json *.json .*.json



6 files checked.  6 passed.  0 failed.
```

**Review by jobara — APPROVED** [review]

**Pull request merged**
