### PR TITLE
Fluid 6548: Replace valid-jsdoc rules with eslint-plugin-jsdoc

### PR DESCRIPTION
**Pull request by jobara**
Splits the configuration for eslint and the jsdoc plugin, but provides a combined configuration to use by default. The valid-jsdoc rules that are deprecated have been removed.

* Rules for eslint-plugin-jsdoc can be found in the [README](https://github.com/gajus/eslint-plugin-jsdoc/blob/master/README.md)
* [Comparison between valid-jsdoc and eslint-config-plugin](https://github.com/gajus/eslint-plugin-jsdoc/wiki/Comparison-with-deprecated-JSdoc-related-ESLint-rules)

Parallel Infusion PR: https://github.com/fluid-project/infusion/pull/1013

https://issues.fluidproject.org/browse/FLUID-6548

### CODE REVIEW

**Comment by jobara** [comment]
@amb26 and @the-t-in-rtf could you please take a look at this PR?

**Comment by amb26** [comment]
I tried using this branch to lint itself using "npm run lint" and got the following error:
````
> eslint-config-fluid@2.0.0 lint E:\source\gits\eslint-config-fluid
> grunt lint

Running "eslint:all" (eslint) task
Warning: Failed to load plugin 'jsdoc' declared in '.eslintrc.json » ./.eslintrc-jsdoc.json': Cannot find module 'eslint'
Require stack:
- E:\source\gits\eslint-config-fluid\node_modules\eslint-plugin-jsdoc\dist\rules\checkExamples.js
- E:\source\gits\eslint-config-fluid\node_modules\eslint-plugin-jsdoc\dist\index.js
- E:\source\gits\eslint-config-fluid\node_modules\grunt-eslint\node_modules\eslint\lib\cli-engine\config-array-factory.js
- E:\source\gits\eslint-config-fluid\node_modules\grunt-eslint\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- E:\source\gits\eslint-config-fluid\node_modules\grunt-eslint\node_modules\eslint\lib\cli-engine\cli-engine.js
- E:\source\gits\eslint-config-fluid\node_modules\grunt-eslint\node_modules\eslint\lib\cli-engine\index.js
- E:\source\gits\eslint-config-fluid\node_modules\grunt-eslint\node_modules\eslint\lib\api.js
- E:\source\gits\eslint-config-fluid\node_modules\grunt-eslint\tasks\eslint.js
- E:\source\gits\eslint-config-fluid\node_modules\grunt\lib\grunt\task.js
- E:\source\gits\eslint-config-fluid\node_modules\grunt\lib\grunt.js
- E:\Source\gits\eslint-config-fluid\node_modules\grunt\node_modules\grunt-cli\bin\grunt
- E:\Source\gits\eslint-config-fluid\node_modules\grunt\bin\grunt Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! eslint-config-fluid@2.0.0 lint: `grunt lint`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the eslint-config-fluid@2.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Bosmon\AppData\Roaming\npm-cache\_logs\2020-10-21T20_52_17_187Z-debug.log
````

**Comment by jobara** [comment]
@amb26 I'm not able to reproduce that issue. Perhaps try clearing the node_modules directory and re-installing? Maybe trashing the package-lock.json file too, although that shouldn't be a problem.

**Comment by the-t-in-rtf** [comment]
This may be a variation on the same issues we've seen with other plugins not being visible to grunt.   @amb26, if you install the missing plugin as a dev dependency, does the issue resolve itself?

**Comment by jobara** [comment]
> This may be a variation on the same issues we've seen with other plugins not being visible to grunt. @amb26, if you install the missing plugin as a dev dependency, does the issue resolve itself?

The plugin should be installed as a dependency of this repo, which should be enough to lint itself. Although, as you say, you may need to install the plugin directly in other repos that use this config. I've mentioned that in the README included with this PR for future reference.

**Comment by the-t-in-rtf** [comment]
Good point, sounds like your suggestion might be on the right track.

**Comment by jobara** [comment]
Added renaming of "master" to "main".

**Comment by jobara** [comment]
@the-t-in-rtf and @amb26 can this be merged?

**Comment by the-t-in-rtf** [comment]
I can't merge it, and @amb26 needs to comment on whether he got past the issues he reported.

**Comment by amb26** [comment]
I deleted package-lock.json and reinstalled, and the issue went away. This phenomenon makes me more unhappy about our growing policy of committing these files :(

**Pull request merged**
